### ISSUE TITLE
If items become empty, the cells are not clear

### ISSUE THREAD

**Issue by sgiraud01** [StevenLambion/ui-listView#6]
Hi,
When my ui-listview is bind to a list which become empty, the cells are not clear. so the old cells are still display.
To fix this, I have to manualy clear the cell with the listView object available on option :

```
        vm.uiListOptions.listView.cells = [];
```

Perhaps this could be done in the _clear method of UIListView .

Regards,

**Comment by bmathews** [comment]
Reproduced here: http://jsfiddle.net/Ly55fmnu/

**Comment by sgiraud01** [comment]
I've made a pull request to fix this 
https://github.com/StevenLambion/ui-listView/pull/7

**Comment by StevenLambion** [comment]
Thanks @sgiraud01!  I'll take a look at it ASAP.

**Comment by StevenLambion** [comment]
I've deployed a new version with your fix.
